version: '2'

services:
  webapplication1:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ${CLRDBG_PATH}:/remote_debugger:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  webapplication2:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ${CLRDBG_PATH}:/remote_debugger:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
